name: Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run ruff linter
        run: ruff check .
      
      - name: Run ruff formatter check
        run: ruff format --check .
      
      - name: Run mypy type checker
        run: mypy . --ignore-missing-imports || true
      
      - name: Run markdownlint
        run: markdownlint-cli2 "**/*.md" "#node_modules" "#mqtt" "#amqp"
